### ISSUE TITLE
[suggestion] please add onDrag event

### ISSUE THREAD

**Issue by breadlesscode** [nikolasp/vue-draggable#2]
Hi, 

thanks for your work! Can you add a onDrag option? That would be great =)

greetings

**Comment by nikolasp** [comment]
Hi,
Dragstart option will be added asap. I think tomorrow this option will be accessible. :)
However, onDrop (dragend) callback you can use already...

**Comment by nikolasp** [comment]
@breadlesscode Hi! I've added this and published new version to npm. Test it and close issue if everything is ok. :)

**Comment by breadlesscode** [comment]
Thanks!!! Will test it soon =)

**Comment by breadlesscode** [comment]
Worked. Thanks again!
